### ISSUE TITLE
springcloud内嵌事物

### ISSUE THREAD

**Issue by wuzl807924995** [Dromara/hmily#76]
在请求模型中
  ui->a->b-c 
b无法使用内嵌事物,导致b c 的cancelMethod confirmMethod 都无法执行完全

**Comment by chainren** [comment]
目前我也遇到相同的问题，研读源码会发现在spring cloud的实现里，如果是事务发起方且当前事务上下文不为空，就会选择ConsumeHmilyTransactionHandler去处理，该处理实现是直接调用目标方法，没有将目标方法加入到当前事务的参与者列表中。这样的话，在confirm/cancel阶段，实际上不会执行嵌套的方法的confirm/cancel方法。这个还希望作者 @yu199195 能够帮忙解释一下，是我们用法或理解有问题，还是spring cloud版本实现漏掉了这个场景？
1. 此处如果是事务发起者，使用ConsumeHmilyTransactionHandler处理；
`
//why this code?  because spring cloud invoke has proxy.
            if (context.getRole() == HmilyRoleEnum.SPRING_CLOUD.getCode()) {
                context.setRole(HmilyRoleEnum.START.getCode());
                return ConsumeHmilyTransactionHandler.class;
            }
`
2. ConsumeHmilyTransactionHandler处理方式就是直接调用目标方法
`
public class ConsumeHmilyTransactionHandler implements HmilyTransactionHandler {
    @Override
    public Object handler(final ProceedingJoinPoint point, final HmilyTransactionContext context) throws Throwable {
        return point.proceed();
    }
}
`

3. 那么在这种发起者服务中嵌套的事务场景，就没法把嵌套事务加入进来
`
// 伪代码
class A{
      @Hmily(confirmMethod = "confirmA", cancelMethod = "cancelA")
      methodA() {
           b.methodB(); 
      }
}

class B{
      @Hmily(confirmMethod = "confirmB", cancelMethod = "cancelB")
      methodB() {
           // do something. 
      }
}
`

**Comment by yu199195** [comment]
b.tryB(); 是本地事务，还是RPC调用?

**Comment by chainren** [comment]
> b.tryB(); 是本地事务，还是RPC调用?
这个是本地的一个方法，可能带本地数据库事务也可能没有事务

**Comment by yu199195** [comment]
最新版本已经解决
